### ISSUE TITLE
Unbounded number of processes during build

### ISSUE THREAD

**Issue by nohsheef** [MoAlyousef/zfltk#18]
During the CMake portion of building fltk, I've observed an unbounded number of zig cc processes, which overloads the system unnecessarily and doesn't provide a benefit. Later, while building the zig code, it's correctly limited to number of cores.

**Comment by MoAlyousef** [comment]
That's strange. The only thing I can think of is that zfltk is using `zig cc` and `zig c++` to compile on linux. You can try commenting them out in the build_utils.zig (like for windows), and it will use the installed c++ compiler (g++).

**Comment by nohsheef** [comment]
- Setting `CMAKE_BUILD_PARALLEL_LEVEL=2` made no difference.
- I counted at one point 153 `zig clang` processes during cfltk's build.

**Comment by nohsheef** [comment]
Is it strictly necessary to build libcxx, is that just how the zig toolchain works (is pre-packaged) for linux x86_64?

**Comment by MoAlyousef** [comment]
> Is it strictly necessary to build libcxx, is that just how the zig toolchain works (is pre-packaged) for linux x86_64?

It's how the zig toolchain works when run for the first time.

> I have to ask: would you mind exposing a build flag to set the following for non-Windows platforms?

These are exposed in fltk-rs via feature flags (system-libjpeg, system-zlib, system-libpng).

**Comment by nohsheef** [comment]
Removing `--parallel` solves the issue, as expected. I wouldn't expect CMake's `--parallel` to spawn as many compilers as there are objects (in the dependency graph) that can be built in parallel.

**Comment by nohsheef** [comment]
Maybe on Linux, considering that FLTK is C++ 98, there isn't a strong reason to use zig cc/c++ for building FLTK, and your system gcc will be more than modern enough. Plus, defaulting to the system cc/c++ (usually gcc) would avoid building libcxx. Unless the goal is to avoid linking libstdc++.

**Comment by nohsheef** [comment]
I also tried OPTION_USE_SYSTEM_[PNG,ZLIB,JPEG] ON, which wasn't enough since it failed at the final link step  because it still tried to link -lfltk_png -lfltk_jpeg -lfltk_z. Looks like that isn't a direct mapping to fltk/CMakeLists.txt FLTK_USE_BUILTIN_[PNG,ZLIB,JPEG]=OFF. It was a quick extra test unrelated to parallelism.

**Comment by MoAlyousef** [comment]
> Unless the goal is to avoid linking libstdc++. Does FLTK itself use libstdc++/libcxx at all?

It doesn't. Maybe zfltk shouldn't force the use of the zig cc/c++ toolchain. If needed, devs could set their CC and CXX env variables to zig cc/c++.

> I also tried OPTION_USE_SYSTEM_[PNG,ZLIB,JPEG] ON, which wasn't enough since it failed at the final link step because it still tried to link -lfltk_png -lfltk_jpeg -lfltk_z. Looks like that isn't a direct mapping to fltk/CMakeLists.txt FLTK_USE_BUILTIN_[PNG,ZLIB,JPEG]=OFF. It was a quick extra test unrelated to parallelism.

Yeah this needs to be done via an option and changed also in the zfltk_link function. Building FLTK with different options isn't trivial. In Rust this can be encapsulated using features, in Zig, there's no blessed way of doing things, and things might change between a release and the next. So I'm not really that invested now, waiting for the water to settle.

**Comment by nohsheef** [comment]
Thanks for the new options. As expected it's cmake over-parallelizing since it happens with gcc as well. I learned that `CMAKE_BUILD_PARALLEL_LEVEL` is [only used](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-build-j) if you do not pass -j/--parallel to cmake. The way I read it, if we use `-G Ninja` without `--parallel`, then ninja will take care of applying a resonable limit, and from what I can tell, ninja uses 3 times the number of physical cores by default. If I understand the documentation correctly, then `--parallel` with `-G Ninja` would run `ninja -j`, which I'm not sure if it means ninja's `-j=0` (unlimited).

I think we can parameterize the command in build.zig with and avoid introducing ninja as dependency:

```zig
const cpu_count = try Thread.getCpuCount();
```
