### ISSUE TITLE
Lots of errors trying on FreeBSD 13.0-RELEASE-p4

### ISSUE THREAD

**Issue by devosalain** [MoAlyousef/zfltk#2]
zig build
zig build-simple 
both don't produce something usefull.

**Comment by MoAlyousef** [comment]
Zero for effort. Closing.

**Comment by devosalain** [comment]
I have some logs :),
zig build returns:
zig build                                                                                         0
Warning: error.FileNotFound. The cfltk library will be grabbed and built from source!

-- Configuration Summary for FLTK 1.4.0 generated by CMake 3.21.3 --

-- The following OPTIONAL packages have been found:

 * Doxygen
 * LATEX

-- Static libraries will be built in /home/x/Dirs/Src/Zig/fltk/zfltk/vendor/bin/fltk/lib
-- Shared libraries will not be built (set OPTION_BUILD_SHARED_LIBS=ON to build)
-- Example programs will not be built (set FLTK_BUILD_EXAMPLES=ON to build)

-- End of Configuration Summary --

-- Configuring done
-- Generating done
-- Build files have been written to: /home/x/Dirs/Src/Zig/fltk/zfltk/vendor/bin
Consolidate compiler generated dependencies of target fltk_z
Consolidate compiler generated dependencies of target cfltk
[  0%] Building CXX object CMakeFiles/cfltk.dir/src/cfl.cpp.o
[  2%] Building CXX object CMakeFiles/cfltk.dir/src/cfl_window.cpp.o
[  5%] Built target fltk_z
[  5%] Building CXX object CMakeFiles/cfltk.dir/src/cfl_dialog.cpp.o
[  6%] Building CXX object CMakeFiles/cfltk.dir/src/cfl_draw.cpp.o
[  6%] Building CXX object CMakeFiles/cfltk.dir/src/cfl_menu.cpp.o
[  7%] Building CXX object CMakeFiles/cfltk.dir/src/cfl_font.cpp.o
[  7%] Building CXX object CMakeFiles/cfltk.dir/src/cfl_surface.cpp.o
/home/x/Dirs/Src/Zig/fltk/zfltk/vendor/cfltk/src/cfl_window.cpp:10:10: fatal error: 'X11/Xatom.h' file not found

**Comment by devosalain** [comment]
zig build run-simple returns the same error

**Comment by devosalain** [comment]
Xatom.h can be found in freebsd in /usr/local/include/X11

**Comment by MoAlyousef** [comment]
If you're using zig as a C compiler, it might not be searching /usr/local/include. It's also better to use the system's default compiler.

Searching online, Freebsd also seems to have this issue in general:
https://wiki.freebsd.org/WarnerLosh/UsrLocal

Anyways, you can try:
```
$ export CPATH=/usr/local/include
$ export LIBRARY_PATH=/usr/local/lib
```
And see if this resolves the cfltk build step.
