### ISSUE TITLE
Error when setting a draw handler with `widget.setDrawHandlerEx`

### ISSUE THREAD

**Issue by TibboddiT** [MoAlyousef/zfltk#21]
I assume there is a typo on this line :

https://github.com/MoAlyousef/zfltk/blob/main/src/widget.zig#L318 :

```zig
container[0] = @intFromPtr(&f);
container[1] = @intFromPtr(d);
```

It seems to me it should look like :

```zig
container[0] = @intFromPtr(f);
container[1] = @intFromPtr(d);
```

**Comment by MoAlyousef** [comment]
Yes indeed. Would you like to create a PR, or should I fix it directly?
