### ISSUE TITLE
Demo Compilation Failure on Windows

### ISSUE THREAD

**Issue by mochalins** [MoAlyousef/zfltk#26]
Using the latest commit on `main` and the latest update to Windows 10, I'm running into compilation issues when attempting to build and run the demos.

I have CMake, Ninja, and MSVC all available in path; building the C bindings to FLTK appeared to be successful.

The exact commands I used to encounter this error were:
```
git clone https://github.com/MoAlyousef/zfltk
cd zfltk
zig build run-simple
```

More details of the error have been included below. 

<details><summary>Details</summary>
<p>
Build Summary: 5/8 steps succeeded; 1 failed (disable with --summary none) <br />
run-simple transitive failure <br />
└─ run simple transitive failure <br />
   └─ zig build-exe simple Debug native 8 errors <br />
error: lld-link: undefined symbol: __declspec(dllimport) __stdio_common_vfprintf <br />
    note: referenced by fltk.lib(Fl_System_Driver.cxx.obj):($LN4) <br />
    note: referenced by fltk.lib(Fl_System_Driver.cxx.obj):($LN6) <br />
    note: referenced by fltk.lib(Fl_System_Driver.cxx.obj):($LN8) <br />
    note: referenced 5 more times <br />
error: lld-link: undefined symbol: __declspec(dllimport) round <br />
    note: referenced by fltk.lib(Fl_win32.cxx.obj):($LN90) <br />
    note: referenced by fltk.lib(Fl_win32.cxx.obj):($LN90) <br />
    note: referenced by fltk.lib(Fl_win32.cxx.obj):($LN90) <br />
    note: referenced 9 more times <br />
error: lld-link: undefined symbol: __declspec(dllimport) __stdio_common_vsscanf <br />
    note: referenced by fltk.lib(Fl_Pixmap.cxx.obj):($LN4) <br />
    note: referenced by fltk.lib(Fl_Pixmap.cxx.obj):($LN6) <br />
    note: referenced by fltk_images.lib(Fl_SVG_Image.cxx.obj) <br />
    note: referenced 2 more times <br />
error: lld-link: undefined symbol: __declspec(dllimport) lround <br />
    note: referenced by fltk_images.lib(Fl_Anim_GIF_Image.cxx.obj):($LN46) <br />
    note: referenced by fltk_images.lib(Fl_Anim_GIF_Image.cxx.obj):($LN46) <br />
    note: referenced by fltk_images.lib(Fl_Anim_GIF_Image.cxx.obj):($LN46) <br />
    note: referenced 15 more times <br />
error: lld-link: undefined symbol: __declspec(dllimport) __stdio_common_vfscanf <br />
    note: referenced by fltk_images.lib(Fl_PNM_Image.cxx.obj):($LN4) <br />
    note: referenced by fltk_images.lib(Fl_PNM_Image.cxx.obj):($LN6) <br />
error: lld-link: undefined symbol: __declspec(dllimport) roundf <br />
    note: referenced by fltk_images.lib(Fl_SVG_Image.cxx.obj):(unsigned int __cdecl nsvg__parseColorRGB(char const *)) <br />
    note: referenced by fltk_images.lib(Fl_SVG_Image.cxx.obj):(unsigned int __cdecl nsvg__parseColorRGB(char const *)) <br />
    note: referenced by fltk_images.lib(Fl_SVG_Image.cxx.obj):(unsigned int __cdecl nsvg__parseColorRGB(char const *)) <br />
error: lld-link: undefined symbol: __declspec(dllimport) __stdio_common_vsprintf <br />
    note: referenced by fltk.lib(Fl_Screen_Driver.cxx.obj):($LN4) <br />
    note: referenced by fltk.lib(vsnprintf.c.obj):($LN4) <br />
    note: referenced 4 more times <br />
error: lld-link: undefined symbol: __declspec(dllimport) _wsopen_dispatch <br />
    note: referenced by fltk.lib(Fl_WinAPI_System_Driver.cxx.obj):($LN18) <br />
    note: referenced by fltk.lib(Fl_WinAPI_System_Driver.cxx.obj):($LN4) <br />
</p>
</details>

**Comment by MoAlyousef** [comment]
The undefined symbols are part of the universal C runtime on windows, it’s strange that the lld linker can’t find them. 

What version of Zig are you using?

Also can you check that you have the windows 10 sdk installed (it should appear in you visual studio installer)?

**Comment by mochalins** [comment]
I'm using the latest main branch (0.12.XX-XX) version of Zig. All relevant Windows SDKs/tools are installed, and I used the Developer Powershell to ensure that all installations were available in Path.

**Comment by MoAlyousef** [comment]
Hopefully the upcoming weekend I’ll update my zig toolchain and try on a windows machine.

**Comment by MoAlyousef** [comment]
I’m not sure what the issue is, but for some reason the CI which worked for windows native stopped working with some obscure linker error messages. I’m guessing it has to do with the zig linker. 
I’ve shifted the CI to use the mingw toolchain on windows and it seems to build correctly on windows. 

The latest zig toolchain doesn’t build on any platform because of changes in the zon package format which I haven’t checked out yet, but it’s too early to chase zig 0.12 since I’m expecting more breaking changes.

**Comment by MoAlyousef** [comment]
Zig 0.12 now works on windows without requiring msys2.
