### ISSUE TITLE
Unable to use zfltk with official Zig package manager

### ISSUE THREAD

**Issue by w568w** [MoAlyousef/zfltk#31]
# Problem

In Zig 0.13.0, it is unable to import the module exported by `sdk.getZfltkModule`. The error is:

```bash
$ zig build run
run
└─ run zfltk-template
   └─ zig build-exe zfltk-template Debug native 1 errors
error: unable to check cache: stat file 'src/zfltk.zig' failed: FileNotFound
error: the following command failed with 1 compilation errors:
/usr/bin/zig build-exe -lcfltk -lfltk -lfltk_images -lfltk_png -lfltk_jpeg -lfltk_z -lfltk_gl -lGL -lGLU -lOpenGL -lX11 -lXext -lXinerama -lXcursor -lXrender -lX11 -lXfixes -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -lXft -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -lfontconfig -lfreetype -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/sysprof-6 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/sysprof-6 -lpangoxft-1.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype -lXft -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -lgobject-2.0 -lglib-2.0 -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/pixman-1 -lcairo -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/sysprof-6 -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lcairo -ODebug -I /home/w568w/Projects/zfltk-test/zig-out/cfltk/include -L /home/w568w/Projects/zfltk-test/zig-out/cfltk/lib/lib -L /home/w568w/Projects/zfltk-test/zig-out/cfltk/lib/lib64 --dep zfltk -Mroot=/home/w568w/Projects/zfltk-test/src/main.zig -I /home/w568w/Projects/zfltk-test/zig-out/cfltk/include -Mzfltk=/home/w568w/Projects/zfltk-test/src/zfltk.zig -lc++ -lc --cache-dir /home/w568w/Projects/zfltk-test/.zig-cache --global-cache-dir /home/w568w/.cache/zig --name zfltk-template --listen=- 
Build Summary: 1/4 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run zfltk-template transitive failure
   └─ zig build-exe zfltk-template Debug native 1 errors
error: the following build command failed with exit code 1:
/home/w568w/Projects/zfltk-test/.zig-cache/o/b1fbc5ebd1e8463d0d33117d79ec1bb1/build /usr/bin/zig /home/w568w/Projects/zfltk-test /home/w568w/Projects/zfltk-test/.zig-cache /home/w568w/.cache/zig --seed 0x4d15fb20 -Zde1162598ec7af8a run
```

# Minimal Working Example 
1. Create a new Zig project;
2. Add `zfltk`'s package URL to `build.zig.zon` according to the README;
3. Add these lines according to the README:

```zig
const sdk = try build_zfltk.init(b);
const zfltk_module = sdk.getZfltkModule(b);
exe.root_module.addImport("zfltk", zfltk_module);
try sdk.link(exe);
```

4. Run `zig build run` and see the error above.

# Additional Information

`sdk.getZfltkModule` in `build.zig` is:

```zig
pub fn getZfltkModule(sdk: *Sdk, b: *Build) *Build.Module {
    _ = sdk;
    var mod = b.createModule(.{
        .root_source_file = b.path("src/zfltk.zig"),
    });
    mod.addIncludePath(b.path("zig-out/cfltk/include"));
    return mod;
}
```

The issue lies with `.root_source_file = b.path("src/zfltk.zig")`. According to the Zig documentation, `(*Build).path(...)` returns a path **relative to the current building package**. Since `b` is passed from my package's `build(b: *std.Build)`, `b.path("src/zfltk.zig")` is evaluated as `<my package root>/src/zfltk.zig`.

Currently, **the officially recommended practice for exporting a module is to call `b.addModule()` within your own `build()` function**. For a minimal example of how to export a package and enable another package to depend on it, you can refer to [this example](https://github.com/JakubSzark/zig-string/blob/master/build.zig).

Another suboptimal solution is to obtain the current file's location using `@src().file` in your `build.zig`, thereby refering to `src/zfltk.zig` by its absolute path. You can refer to [this example](https://github.com/capy-ui/capy/blob/36a3047eacabcb8dc54868ea96b4c3b0f27a8d95/build_capy.zig#L165-L173).

**Comment by MoAlyousef** [comment]
Hi
Thanks for the report.
I've used the prefix method, and tried it and it works with zig 0.13.0.
The `build.dependency` method I don't think will work since zfltk isn't a purely zig dependency.

**Comment by w568w** [comment]
Thanks for your quick response! I have verified that `0.4.0` compiles normally.

However, I have two optional suggestions to further improve the building process:

1. Instead of concatenating path strings with `/`, you can use [`std.fs.path.join`](https://ziglang.org/documentation/master/std/#std.fs.path.join) or [`std.fs.path.sep_str`](https://ziglang.org/documentation/master/std/#std.fs.path.sep_str) to make it platform-agnostic.
2. I observed that the `example` step is included as a dependency of the default step. Therefore, any project depending on `zfltk` will build all examples first, which I find unnecessary:

https://github.com/MoAlyousef/zfltk/blob/152a3d2161d1327a9cee5979a15165d39611a087/build.zig#L82-L83

Is there any particular reason for this?

**Comment by MoAlyousef** [comment]
1- Windows supports forward slash separators. And since these are not user facing, I don’t think it should pose a problem (mixed forward and backslashes). But if it causes build failures I guess I’ll have to use path.join. 

2- It’s a relic  of pre-packages that wasn’t changed. I guess it could be made optional behind an sdk option.

**Comment by w568w** [comment]
Got it. Thanks :)
