### ISSUE TITLE
Switching `Group.add` (and similar functions) to take widgets from value instead of reference

### ISSUE THREAD

**Issue by mgord9518** [MoAlyousef/zfltk#9]
After an [interesting read](https://www.lewisgaul.co.uk/blog/coding/2021/01/10/trying-zig/#:~:text=Structs%2C%20unions%2C%20and%20arrays%20can%20sometimes%20be%20more,reference%2C%20whichever%20way%20Zig%20decides%20will%20be%20faster.), it looks like Zig automatically optimizes to use the fastest option between passing by value or reference, so the main difference appears to be whether you actually need to work with the pointer itself (or mutate the structure).

In this use case, none of the widgets are being modified, so it might make it easier to just pass by value instead and forego the need for stuff like `grp.add(&my_button.asWidget());`. in favor of `grp.add(my_button.asWidget());`

Or another idea, would be having `Group.add` use `anytype`, which then gets resolved at compile time to ensure it's a valid widget. Then any function that takes a widget as a param would be as simple as `grp.add(my_button);`. I can implement it, I'm just asking in case there's reasons they should be passed by reference that I haven't considered

**Comment by MoAlyousef** [comment]
That sounds good, and would be a nice improvement to the api. I haven't been following Zig as closely recently. I'll need to catch up a bit.

> reasons they should be passed by reference that I haven't considered

The only thing I could find online is:
https://github.com/ziglang/zig/issues/5973

So it might affect things like `window.asGroup().resizable(window);`, but I'm not sure.

**Comment by mgord9518** [comment]
@MoAlyousef I think for this situation it shouldn't matter since the widget structs only contain a pointer as data so regardless it'll just be a pointer being copied 

I'll try doing some testing on it to be sure though
